apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "symfony.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "symfony.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: {{ include "symfony.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "symfony.name" . }}
    spec:
      containers:
        - name: symfony
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
