version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://symfony:symfony@db/symfony
    depends_on:
      - db
    networks:
      - symfony_network

  db:
    image: postgres:15-alpine
    container_name: symfony_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
