---
kind: Secret
apiVersion: v1
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-registry-secret
  annotations:
    "argocd.argoproj.io/sync-wave": "-1"
data:
  .dockerconfigjson: <secret_token>
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "symfony.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-1"
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
