apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-symfony-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "my-symfony-chart.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
